@if "%DEBUG%" == "" echo off
REM ==============================================================================
REM  hex_writer.bat — Pure batch PE executable writer (zero external dependencies)
REM
REM  Copyright (c) 2026 lRENyaaa (https://github.com/lRENyaaa)
REM
REM  Licensed under the Apache License, Version 2.0 (the "License");
REM  you may not use this file except in compliance with the License.
REM  You may obtain a copy of the License at
REM 
REM       http://www.apache.org/licenses/LICENSE-2.0
REM 
REM  Unless required by applicable law or agreed to in writing, software
REM  distributed under the License is distributed on an "AS IS" BASIS,
REM  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
REM  See the License for the specific language governing permissions and
REM  limitations under the License.
REM
REM  Generates append_byte.exe byte-by-byte using only cmd.exe internal commands.
REM  No findstr, no certutil, no PowerShell — just cmd.exe and its built-in tools.
REM
REM  Three core techniques:
REM    1. %hex:~N,1% substring indexing  —  OEM-437 char map as a 256-byte LUT
REM    2. cmd /u /c "type X"             —  narrow-byte to wide-char re-interpreter
REM    3. U+1A00 (EOF in /u mode)        —  NUL seed generation with auto-truncation
REM
REM  Byte output strategies (chosen by byte value):
REM    %hex:~N,1%            —  any non-zero byte (except leading 0x20)
REM    narrow byte + /u type —  "XX 00" pair, absorbs odd NUL (XX < 0x80 only)
REM    U+XX00 + /u set/p     —  "00 XX" pair (XX >= 0x80, or 00-first order needed)
REM    prepare0x2000 function  —  "20 00" pair (set/p strips leading spaces)
REM
REM  Auto-generated by Java (exe generation portion). Source: append_byte_fasm.exe
REM  Manually adjusted to handle odd 0x00 bytes and leading 0x20 stripping.
REM
REM  0xCC fill convention: PE header fields that Windows ignores are filled with
REM  0xCC (x86 INT3) instead of 0x00. This reduces the number of NUL bytes the
REM  batch script must generate, since producing 0x00 in pure cmd is expensive.
REM  The exe is pre-processed by build.ps1 to maximize 0xCC coverage before
REM  the Java generator converts it into this batch script.
REM ==============================================================================
setlocal EnableDelayedExpansion
cd /d "%~dp0"
REM  Set UTF-8 early so echo output displays correctly and isn't cleared
REM  by subsequent code-page switches in helper functions.
chcp 65001 >nul

:start

echo [%time%] Preparing...

call :prepareHex
call :prepareNulCache
call :prepare0x2000

REM Original Source: append_byte_fasm.asm
set "fileName=ByteAppender.exe"
set "targetName=0-255.bin"
type nul > "%fileName%"
type nul > "%targetName%"

echo [%time%] Building %fileName%...

REM ============================== DOS Header & DOS Stub ==============================
REM  DOS e_magic("MZ") + e_cblp(0xCC80) + e_cp(0xCC01) + e_crlc(0xCCCC)
REM  e_cparhdr(0xCC04) + e_minalloc(0xCC10) + e_maxalloc(0xFFFF) + e_ss/e_sp etc.
REM  All reserved/filler DOS fields pre-filled with 0xCC to minimize zero runs.
REM  %hex:~204,1% = 0xCC (INT3), the standard "safe non-zero" filler for this PE.
<nul set /p ="%hex:~77,1%%hex:~90,1%%hex:~128,1%%hex:~204,1%%hex:~1,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~4,1%%hex:~204,1%%hex:~16,1%%hex:~204,1%%hex:~255,1%%hex:~255,1%%hex:~204,1%%hex:~204,1%%hex:~64,1%%hex:~1,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~64,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  DOS e_res/e_res2: 0xCC fill + e_lfanew(PE offset = 0x80)
<nul set /p ="%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~128,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  DOS stub: 0x0E 0x1F 0xBA 0x0E — disassembles to PUSH CS; POP DS; MOV DX,0E; ...
REM  0x00 0E pair via U+0E00 → /u set/p (00-first order required)
cmd /u /c "<nul set /p =%hex000e%">> "%fileName%"
<nul set /p ="%hex:~31,1%%hex:~186,1%%hex:~14,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  DOS stub message: "This program cannot be run in DOS mode.\r\n$"
REM  Followed by 7×0xCC fill + PE\0\0 signature
<nul set /p ="%hex:~180,1%%hex:~9,1%%hex:~205,1%%hex:~33,1%%hex:~184,1%%hex:~1,1%%hex:~76,1%%hex:~205,1%%hex:~33,1%%hex:~84,1%%hex:~104,1%%hex:~105,1%%hex:~115,1%%hex:~32,1%%hex:~112,1%%hex:~114,1%%hex:~111,1%%hex:~103,1%%hex:~114,1%%hex:~97,1%%hex:~109,1%%hex:~32,1%%hex:~99,1%%hex:~97,1%%hex:~110,1%%hex:~110,1%%hex:~111,1%%hex:~116,1%%hex:~32,1%%hex:~98,1%%hex:~101,1%%hex:~32,1%%hex:~114,1%%hex:~117,1%%hex:~110,1%%hex:~32,1%%hex:~105,1%%hex:~110,1%%hex:~32,1%%hex:~68,1%%hex:~79,1%%hex:~83,1%%hex:~32,1%%hex:~109,1%%hex:~111,1%%hex:~100,1%%hex:~101,1%%hex:~46,1%%hex:~13,1%%hex:~10,1%%hex:~36,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~80,1%%hex:~69,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM ============================== PE Signature & COFF Header ==============================
REM  Machine=0x014C(x86), NumberOfSections=2, SizeOfOptionalHeader=0xE0=224
<nul set /p ="%hex:~76,1%%hex:~1,1%">> "%fileName%"
REM  0x02 00 = NumberOfSections(2). Narrow byte + /u type produces "02 00" pair.
REM  This pattern absorbs the following odd NUL into a 2-byte even pair, letting
REM  the NUL cache use only even-sized blocks (no findstr-based odd-NUL generator).
<nul set /p ="%hex:~2,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
REM  TimeDateStamp: 0x6A2491EF (deprecated PE fields fill: 8×0xCC)
REM  SizeOfOptionalHeader(224=0xE0) — E0 from plain hex above, then 00 from U+0F00 below
REM  where the 0F byte also starts Characteristics(0x010F). (00-first order for WORD layout)
<nul set /p ="%hex:~239,1%%hex:~145,1%%hex:~36,1%%hex:~106,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~224,1%">> "%fileName%"
cmd /u /c "<nul set /p =%hex000f%">> "%fileName%"
REM  Characteristics: 0x010F — IMAGE_FILE_EXECUTABLE | 32BIT | RELOCS_STRIPPED | LINE_NUMS_STRIPPED
REM  This line also writes Magic(0x010B) and MajorLinkerVersion=1 (shared 01 byte).
<nul set /p ="%hex:~1,1%%hex:~11,1%%hex:~1,1%%hex:~1,1%">> "%fileName%"
REM  MinorLinkerVersion=0x49 via /u type, absorbed NUL starts SizeOfCode(0x200).
<nul set /p ="%hex:~73,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
REM  SizeOfCode continues: 02 00 via /u type.
<nul set /p ="%hex:~2,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  SizeOfCode end + SizeOfInitData start.
REM  SizeOfInitData=0x200 — 0x02 + NUL padding.
<nul set /p ="%hex:~2,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM ============================== PE Optional Header ==============================
REM  SizeOfUninitData=0 (0xCC fill + shared NUL with EntryPoint RVA below)
<nul set /p ="%hex:~204,1%%hex:~204,1%%hex:~204,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  SizeOfUninitData=0 (pre-filled with 0xCC, 4B)
REM  EntryPoint RVA=0x1000: 00 10 via /u type → "10 00" (absorbs NUL)
<nul set /p ="%hex:~16,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  BaseOfCode RVA=0x1000: 00 10 via /u type
<nul set /p ="%hex:~16,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  BaseOfData (0xCC overwritten, field unused for this PE)
<nul set /p ="%hex:~204,1%">> "%fileName%"
type "nul_cache\nul_4.bin" >> "%fileName%"
REM  ImageBase=0x400000: 00 40 via /u type + zero bytes
REM    (Byte order in PE is little-endian: 00 00 40 00)
<nul set /p ="%hex:~64,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  SectionAlignment=0x1000: 00 10 via /u type
<nul set /p ="%hex:~16,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  FileAlignment=0x200 (2 × NUL absorption via /u type)
<nul set /p ="%hex:~2,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  MajorOSVersion=1, MajorSubsystemVersion=3
<nul set /p ="%hex:~1,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  MinorOSVersion/MinorImageVer/MinorSubVer: 0xCC filled (6B of CC)
<nul set /p ="%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~3,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  Win32Version=0 (0xCC fill 4B)
<nul set /p ="%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  SizeOfImage=0x3000: 00 30 via /u type
<nul set /p ="%hex:~48,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  SizeOfHeaders=0x200
<nul set /p ="%hex:~2,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  CheckSum=0 (0xCC fill 4B)
<nul set /p ="%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~3,1%">> "%fileName%"
type "nul_cache\nul_4.bin" >> "%fileName%"
REM  Subsystem=0x03(Console), DllChar=0
<nul set /p ="%hex:~16,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  StackReserve=0x1000: 0x10 via /u type
<nul set /p ="%hex:~16,1%">> "%fileName%"
type "nul_cache\nul_4.bin" >> "%fileName%"
REM  HeapReserve/HeapCommit/LoaderFlags: partly 0xCC filled
<nul set /p ="%hex:~1,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM ============================== Section Table & .text Section ==============================
REM  DataDirectory[Import]: RVA=0x2000, Size=0xAA
REM  DD[Resource..15]: all zero (PE requires 16 entries, rest unused)
<nul set /p ="%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~16,1%">> "%fileName%"
type "nul_cache\nul_12.bin" >> "%fileName%"
REM  .text section header: VirtualSize(0xE0), VirtualAddress(0x1000),
REM  RawSize(0x0200), RawOffset(0x0200)
REM  .text Characteristics: 0x60000020 (CODE|EXECUTE|READ|CNT_CODE|MEM_EXECUTE|MEM_READ)
REM    Begins with 0x20 — needs prepare0x2000 trick for leading space byte
type "0x2000.bin" >> "%fileName%"
cmd /u /c "<nul set /p =%hex00aa%">> "%fileName%"
type "nul_cache\nul_114.bin" >> "%fileName%"
REM  .text section name: ".extt\0\0\0" — 8 bytes ASCIZ, leading 0x2E via U+2E00
cmd /u /c "<nul set /p =%hex002e%">> "%fileName%"
<nul set /p ="%hex:~101,1%%hex:~120,1%%hex:~116,1%">> "%fileName%"
REM  Section name trailing NULs absorbed via /u type
<nul set /p ="%hex:~116,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  .text VirtualSize=0xE0
<nul set /p ="%hex:~224,1%">> "%fileName%"
type "nul_cache\nul_4.bin" >> "%fileName%"
REM  .text VirtualAddress=0x1000: 00 10 via /u type
<nul set /p ="%hex:~16,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  .text RawSize=0x0200: 00 02 via /u type (absorbs NUL)
<nul set /p ="%hex:~2,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  .text RawOffset=0x0200
<nul set /p ="%hex:~2,1%">> "%fileName%"
type "nul_cache\nul_10.bin" >> "%fileName%"
REM  .text Characteristics=0x60000020
<nul set /p ="%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~32,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  .idata section name: ".idata\0\0" — 8 bytes ASCIZ, leading 0x2E via plain hex
<nul set /p ="%hex:~96,1%%hex:~46,1%%hex:~105,1%%hex:~100,1%%hex:~97,1%%hex:~116,1%%hex:~97,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  .idata VirtualSize=0x00AA
<nul set /p ="%hex:~170,1%">> "%fileName%"
type "nul_cache\nul_4.bin" >> "%fileName%"
REM  .idata VirtualAddress=0x2000 (leading 0x20 via prepare0x2000)
type "0x2000.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  .idata RawSize=0x0200
<nul set /p ="%hex:~2,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  .idata RawOffset=0x0400: 00 04 via U+0400 (/u set/p)
cmd /u /c "<nul set /p =%hex0004%">> "%fileName%"
type "nul_cache\nul_10.bin" >> "%fileName%"
REM  .idata Characteristics=0xC0000040 (INITIALIZED_DATA|READ)
<nul set /p ="%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~204,1%%hex:~64,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  Section-to-file alignment padding: 0x3000 C0 fill
<nul set /p ="%hex:~192,1%">> "%fileName%"
type "nul_cache\nul_56.bin" >> "%fileName%"
REM  Zero-free x86 machine code (append_byte_fasm, XOR-obfuscated API calls).
REM  All push-immediate-zero eliminated (xor eax,eax; push eax instead).
REM  push 128 eliminated (push 127; inc [esp] instead).
REM  IAT absolute addresses eliminated (xor reg,key; mov reg,[IAT] via computed addr).
REM  224 bytes of code with zero 0x00 bytes in the entire instruction stream.
<nul set /p ="%hex:~184,1%%hex:~105,1%%hex:~97,1%%hex:~1,1%%hex:~65,1%%hex:~53,1%%hex:~65,1%%hex:~65,1%%hex:~65,1%%hex:~65,1%%hex:~139,1%%hex:~16,1%%hex:~255,1%%hex:~210,1%%hex:~137,1%%hex:~199,1%%hex:~49,1%%hex:~192,1%%hex:~138,1%%hex:~15,1%%hex:~71,1%%hex:~128,1%%hex:~249,1%%hex:~32,1%%hex:~116,1%%hex:~4,1%%hex:~132,1%%hex:~201,1%%hex:~117,1%%hex:~244,1%%hex:~128,1%%hex:~63,1%%hex:~32,1%%hex:~117,1%%hex:~3,1%%hex:~71,1%%hex:~235,1%%hex:~248,1%%hex:~137,1%%hex:~254,1%%hex:~138,1%%hex:~15,1%%hex:~71,1%%hex:~128,1%%hex:~249,1%%hex:~32,1%%hex:~116,1%%hex:~4,1%%hex:~132,1%%hex:~201,1%%hex:~117,1%%hex:~244,1%%hex:~136,1%%hex:~71,1%%hex:~255,1%%hex:~128,1%%hex:~63,1%%hex:~32,1%%hex:~117,1%%hex:~3,1%%hex:~71,1%%hex:~235,1%%hex:~248,1%%hex:~80,1%%hex:~106,1%%hex:~127,1%%hex:~255,1%%hex:~4,1%%hex:~36,1%%hex:~106,1%%hex:~4,1%%hex:~80,1%%hex:~80,1%%hex:~106,1%%hex:~4,1%%hex:~86,1%%hex:~184,1%%hex:~109,1%%hex:~97,1%%hex:~1,1%%hex:~65,1%%hex:~53,1%%hex:~65,1%%hex:~65,1%%hex:~65,1%%hex:~65,1%%hex:~139,1%%hex:~16,1%%hex:~255,1%%hex:~210,1%%hex:~137,1%%hex:~195,1%%hex:~49,1%%hex:~192,1%%hex:~106,1%%hex:~2,1%%hex:~80,1%%hex:~80,1%%hex:~83,1%%hex:~184,1%%hex:~113,1%%hex:~97,1%%hex:~1,1%%hex:~65,1%%hex:~53,1%%hex:~65,1%%hex:~65,1%%hex:~65,1%%hex:~65,1%%hex:~139,1%%hex:~16,1%%hex:~255,1%%hex:~210,1%%hex:~131,1%%hex:~236,1%%hex:~8,1%%hex:~128,1%%hex:~63,1%%hex:~32,1%%hex:~117,1%%hex:~3,1%%hex:~71,1%%hex:~235,1%%hex:~248,1%%hex:~138,1%%hex:~7,1%%hex:~44,1%%hex:~48,1%%hex:~60,1%%hex:~10,1%%hex:~115,1%%hex:~56,1%%hex:~49,1%%hex:~201,1%%hex:~15,1%%hex:~182,1%%hex:~7,1%%hex:~71,1%%hex:~44,1%%hex:~48,1%%hex:~60,1%%hex:~10,1%%hex:~115,1%%hex:~7,1%%hex:~107,1%%hex:~201,1%%hex:~10,1%%hex:~1,1%%hex:~193,1%%hex:~235,1%%hex:~239,1%%hex:~136,1%%hex:~12,1%%hex:~36,1%%hex:~106,1%%hex:~1,1%%hex:~255,1%%hex:~12,1%%hex:~36,1%%hex:~141,1%%hex:~68,1%%hex:~36,1%%hex:~8,1%%hex:~80,1%%hex:~106,1%%hex:~1,1%%hex:~141,1%%hex:~68,1%%hex:~36,1%%hex:~12,1%%hex:~80,1%%hex:~83,1%%hex:~184,1%%hex:~117,1%%hex:~97,1%%hex:~1,1%%hex:~65,1%%hex:~53,1%%hex:~65,1%%hex:~65,1%%hex:~65,1%%hex:~65,1%%hex:~139,1%%hex:~16,1%%hex:~255,1%%hex:~210,1%%hex:~235,1%%hex:~184,1%%hex:~49,1%%hex:~192,1%%hex:~83,1%%hex:~184,1%%hex:~121,1%%hex:~97,1%%hex:~1,1%%hex:~65,1%%hex:~53,1%%hex:~65,1%%hex:~65,1%%hex:~65,1%%hex:~65,1%%hex:~139,1%%hex:~16,1%%hex:~255,1%%hex:~210,1%%hex:~106,1%%hex:~1,1%%hex:~255,1%%hex:~12,1%%hex:~36,1%%hex:~184,1%%hex:~125,1%%hex:~97,1%%hex:~1,1%%hex:~65,1%%hex:~53,1%%hex:~65,1%%hex:~65,1%%hex:~65,1%%hex:~65,1%%hex:~139,1%%hex:~16,1%%hex:~255,1%%hex:~210,1%">> "%fileName%"
type "nul_cache\nul_300.bin" >> "%fileName%"
REM ============================== .idata Section ==============================
REM  Import Directory Table: one descriptor (KERNEL32.DLL) + null terminator.
REM  INT/IAT fields: RVA arrays terminated by null DWORD.
<nul set /p ="%hex:~68,1%%hex:~32,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
<nul set /p ="%hex:~40,1%%hex:~32,1%">> "%fileName%"
REM  Import Directory null terminator (20 zero bytes)
type "nul_cache\nul_22.bin" >> "%fileName%"
<nul set /p ="%hex:~81,1%%hex:~32,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
<nul set /p ="%hex:~99,1%%hex:~32,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
<nul set /p ="%hex:~113,1%%hex:~32,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
<nul set /p ="%hex:~130,1%%hex:~32,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
<nul set /p ="%hex:~142,1%%hex:~32,1%">> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
<nul set /p ="%hex:~156,1%%hex:~32,1%">> "%fileName%"
type "nul_cache\nul_6.bin" >> "%fileName%"
REM Hint/Name table — ordinal(2B) + function name string, null-terminated
REM KERNEL32.DLL name
<nul set /p ="%hex:~75,1%%hex:~69,1%%hex:~82,1%%hex:~78,1%%hex:~69,1%%hex:~76,1%%hex:~51,1%%hex:~50,1%%hex:~46,1%%hex:~68,1%%hex:~76,1%">> "%fileName%"
<nul set /p ="%hex:~76,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  GetCommandLineA, trailing NUL absorbed via /u type
<nul set /p ="%hex:~71,1%%hex:~101,1%%hex:~116,1%%hex:~67,1%%hex:~111,1%%hex:~109,1%%hex:~109,1%%hex:~97,1%%hex:~110,1%%hex:~100,1%%hex:~76,1%%hex:~105,1%%hex:~110,1%%hex:~101,1%">> "%fileName%"
<nul set /p ="%hex:~65,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  CreateFileA, trailing NUL absorbed via /u type
<nul set /p ="%hex:~67,1%%hex:~114,1%%hex:~101,1%%hex:~97,1%%hex:~116,1%%hex:~101,1%%hex:~70,1%%hex:~105,1%%hex:~108,1%%hex:~101,1%">> "%fileName%"
<nul set /p ="%hex:~65,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  SetFilePointer, trailing NUL absorbed via /u type
<nul set /p ="%hex:~83,1%%hex:~101,1%%hex:~116,1%%hex:~70,1%%hex:~105,1%%hex:~108,1%%hex:~101,1%%hex:~80,1%%hex:~111,1%%hex:~105,1%%hex:~110,1%%hex:~116,1%%hex:~101,1%">> "%fileName%"
<nul set /p ="%hex:~114,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  WriteFile, trailing NUL absorbed via /u type
<nul set /p ="%hex:~87,1%%hex:~114,1%%hex:~105,1%%hex:~116,1%%hex:~101,1%%hex:~70,1%%hex:~105,1%%hex:~108,1%">> "%fileName%"
<nul set /p ="%hex:~101,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  CloseHandle, trailing NUL absorbed via /u type
<nul set /p ="%hex:~67,1%%hex:~108,1%%hex:~111,1%%hex:~115,1%%hex:~101,1%%hex:~72,1%%hex:~97,1%%hex:~110,1%%hex:~100,1%%hex:~108,1%">> "%fileName%"
<nul set /p ="%hex:~101,1%">tmp.bin
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_2.bin" >> "%fileName%"
REM  ExitProcess, trailing NUL absorbed via /u type
<nul set /p ="%hex:~69,1%%hex:~120,1%%hex:~105,1%%hex:~116,1%%hex:~80,1%%hex:~114,1%%hex:~111,1%%hex:~99,1%%hex:~101,1%%hex:~115,1%">> "%fileName%"
<nul set /p ="%hex:~115,1%">tmp.bin
REM  File end: exit code + section alignment padding (342 NUL)
cmd /u /c "type tmp.bin" >> "%fileName%"
type "nul_cache\nul_342.bin" >> "%fileName%"

REM ============================== Cleanup & Verification ==============================
REM  Delete temporary files and NUL cache directory
del /f /q tmp.bin >nul 2>&1
del /f /q 0x2000.bin >nul 2>&1
rmdir /s /q nul_cache 2>nul

echo [%time%] %fileName% Built.

REM Verify: check file size is exactly 1536 bytes before running
for %%I in ("%fileName%") do set "exeSize=%%~zI"
if not "!exeSize!"=="1536" (
    echo [%time%] ERROR: %fileName% size is !exeSize! bytes, expected 1536. Retrying...
    goto :start
)

REM Use the just-built exe to generate a 0-255 test file
%fileName% %targetName% 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243 244 245 246 247 248 249 250 251 252 253 254 255

echo [%time%] Write %targetName% Done.

if "%NOPAUSE%" == "" (
    echo [%time%] Press any key to exit...
    pause >nul
)

goto :eof

REM ============================== Helper Functions ==============================
REM Build the %hex% lookup table: each character at position N, when written
REM to a file with chcp 437, produces byte value N.
REM   Switch to UTF-8 to set the multi-byte string, then back to OEM-437.
REM Design constraint: cmd internal commands (set, echo, for) use C-style
REM   \0-terminated strings — variables cannot hold a bare 0x00 byte.
REM   NUL must be produced at the I/O boundary (stdout), not stored in a variable.
REM
REM   Two methods to produce 0x00 alongside a non-zero byte:
REM     [1] U+XX00 chars  →  UTF-16LE "00 XX"  →  cmd /u /c "<nul set /p =CHAR"
REM         Used when we need 00 XX order, or when XX >= 0x80.
REM     [2] narrow byte   →  /u type reinterpret  →  "XX 00"
REM         Used when XX < 0x80 (safe code-page round-trip). Absorbs odd NUL.
REM
REM   Method [2] is preferred wherever possible — it avoids introducing new
REM   Unicode characters and uses the same hex lookup table as normal bytes.
:prepareHex
chcp 65001 >nul
REM  256-byte OEM-437 mapping indexed by %hex:~N,1%
set "hex=-☺☻♥♦♣♠•◘○◙♂♀♪♫☼►◄↕‼¶§▬↨↑↓→←∟↔▲▼ ！“#$％%&'()*+,-./0123456789：；＜＝＞？@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]＾_`abcdefghijklmnopqrstuvwxyz{｜}~⌂ÇüéâäàåçêëèïîìÄÅÉæÆôöòûùÿÖÜ¢£¥₧ƒáíóúñÑªº¿⌐¬½¼¡«»░▒▓│┤╡╢╖╕╣║╗╝╜╛┐└┴┬├─┼╞╟╚╔╩╦╠═╬╧╨╤╥╙╘╒╓╫╪┘┌█▄▌▐▀αßΓπΣσµτΦΘΩδ∞φε∩≡±≥≤⌠⌡÷≈°∙·√ⁿ²■ "
REM  U+XX00 chars → UTF-16LE "00 XX" in /u mode.
REM  Only needed when XX >= 0x80 (UTF-8 multi-byte, unsafe for /u type round-trip)
REM  or when "00 XX" order is required instead of "XX 00".
REM U+0E00 → 00 0E (DOS stub signature prefix)
set "hex000e=฀"
REM U+0F00 → 00 0F (SizeOfOptionalHeader LSB)
set "hex000f=ༀ"
REM U+2E00 → 00 2E ('.' = .text section name prefix)
set "hex002e=⸀"
REM U+1A00 → 00 1A (EOF seed: /u type strips it, leaves 00 00)
set "hex001a=ᨀ"
REM U+0400 → 00 04 (idata field)
set "hex0004=Ѐ"
REM U+1A20 → 20 1A (seed for 20 00 pair via /u type)
set "hex201a=ᨠ"
REM U+AA00 → 00 AA (fill byte)
set "hex00aa=ꨀ"
chcp 437 >nul
goto :eof

REM Build all NUL-byte cache files from a single 00 1A seed, no external tools needed.
REM   Step 1: U+1A00 → /u set/p → 00 1A (raw)
REM   Step 2: 00 1A → /u type → 00 00  (U+001A=EOF in /u text mode, stripped)
REM   Step 3: copy /b doubling + composition for all required even sizes
:prepareNulCache
mkdir nul_cache 2>nul
pushd nul_cache

REM Generate seed NUL pair: 00 1A → /u type → 00 00
cmd /u /c "<nul set /p =%hex001a%">0x001a.bin
cmd /u /c "type 0x001a.bin">nul_2.bin

REM Clean temp file
del /f /q 0x001a.bin >nul 2>&1

REM Power-of-2 doubling chain
copy /b nul_2.bin + nul_2.bin nul_4.bin >nul
copy /b nul_4.bin + nul_4.bin nul_8.bin >nul
copy /b nul_8.bin + nul_8.bin nul_16.bin >nul
copy /b nul_16.bin + nul_16.bin nul_32.bin >nul
copy /b nul_32.bin + nul_32.bin nul_64.bin >nul
copy /b nul_64.bin + nul_64.bin nul_128.bin >nul
copy /b nul_128.bin + nul_128.bin nul_256.bin >nul
REM Composite sizes — all EVEN. Odd-sized NUL blocks (nul_1, nul_3,
REM nul_115, nul_343 from the original writer.bat with findstr) were
REM eliminated by absorbing one adjacent byte into each NUL region.
REM The adjacent byte + 0x00 is written as a single "XX 00" pair via
REM /u type in the main body, avoiding the need for an odd-size cache.
REM See the "XX 00 via /u type" pattern throughout the writer body.
copy /b nul_2.bin + nul_8.bin nul_10.bin >nul
copy /b nul_4.bin + nul_8.bin nul_12.bin >nul
copy /b nul_2.bin + nul_2.bin + nul_2.bin nul_6.bin >nul
copy /b nul_16.bin + nul_4.bin + nul_2.bin nul_22.bin >nul
copy /b nul_32.bin + nul_16.bin + nul_8.bin nul_56.bin >nul
copy /b nul_64.bin + nul_32.bin + nul_16.bin + nul_2.bin nul_114.bin >nul
copy /b nul_256.bin + nul_32.bin + nul_8.bin + nul_4.bin nul_300.bin >nul
copy /b nul_256.bin + nul_64.bin + nul_16.bin + nul_4.bin + nul_2.bin  nul_342.bin >nul
popd
goto :eof

REM prepare0x2000 — Generate "20 00" byte pair (0x20 + NUL).
REM
REM   In this script, 0x00 bytes are produced via even-sized nul_cache files.
REM   After a nul_cache append, the file ends at a NUL byte. If the very next
REM   byte to write is 0x20, <nul set /p will treat it as a leading space and
REM   strip it — a boundary case where 0x20 immediately follows a 0x00 region.
REM
REM   The narrow-byte + /u type trick also fails for 0x20.
REM
REM   The solution relies on a specific property of this PE file: every
REM   boundary 0x20 appears as a single byte sandwiched between two 0x00
REM   regions — the pattern "00 20 00". Instead of producing the 0x20 alone
REM   (which set/p would strip), we produce "20 00" as a pair via 0x2000.bin,
REM   leaving the surrounding 0x00 bytes to the normal nul_cache.
REM
REM   Mechanism: same U+1A00 seed trick as NUL generation.
REM     U+1A20 → /u set/p → 20 1A  →  /u type → 20 00
REM     U+001A (= 1A 00 in UTF-16LE) is the EOF character in /u text mode.
REM     /u type hits it and stops, truncating output to just "20 00".
REM
REM   Called once at startup; the resulting 0x2000.bin (contains "20 00") is
REM   used inline wherever a PE field begins with 0x20 (e.g., .text
REM   Characteristics, .idata VirtualAddress).
:prepare0x2000

REM Generate seed 0x20 0x00: 20 1A → /u type → 20 00
cmd /u /c "<nul set /p =%hex201a%">0x201a.bin
cmd /u /c "type 0x201a.bin">0x2000.bin

REM Clean temp file
del /f /q 0x201a.bin >nul 2>&1
goto :eof